### ISSUE TITLE
关于 联系人搜索为空 可能崩溃的解决办法

### ISSUE THREAD

**Issue by Likeyong** [Othershe/GroupIndexLib#3]
最近在做联系人搜索，没想到找到了这么强大的库。满足了我的所有需求，在做的时候遇到了点问题：在搜索联系人如果结果为空。就会报数组越界的bug

出现这个原因是，因为当搜索出的List集合  和原本的list  数据不一样，所以设置了新的GroupHeadItemDecoration。这时候recyclerview  就添加了两个itemDecoration 。所以就出现了这个问题。
解决这个问题的方案是：在添加新的GroupHeadItemDecoration 的时候  一定要调用recyclerview.removeItemDecoration（）移除上一个GroupHeadItemDecoration 
因为在解决这个问题行用了一段时间，所以记录一下。

**Comment by shehuan** [comment]
我刚也测试了，你这种情况下确实需要移除之前的ItemDecoration，感谢分享

**Comment by roybill** [comment]
@Likeyong  你好,我也遇到了这种情况,就是姓名或手机号为空的时候,请问你这个removeItemDecoration()大致放到哪个位置?还有里面的参数怎么写呢?

**Comment by Likeyong** [comment]
> @Likeyong 你好,我也遇到了这种情况,就是姓名或手机号为空的时候,请问你这个removeItemDecoration()大致放到哪个位置?还有里面的参数怎么写呢?

比如一个recyclerview 里面有{ 11,12,23,24,25}这些数据,然后搜索包含"1"的item,搜索结果为{11,12}.然后你要显示{11,12},这两个数据你也会给他设置头,所以应该在你将新list设置给recyclerview时,移除recyclerview之前所有的分割线

**Comment by roybill** [comment]
我大致是这样写的,但是不行,应该怎么改呢?
`       SortHelper<ItemData> sortHelper = new SortHelper<ItemData>() {
            @Override
            public String sortField(ItemData data) {
                return data.getTitle();
            }
        };

        //todo: 注意手机号或姓名为null的情况
            sortHelper.sortByLetter(datas);
            final List<String> tags = sortHelper.getTags(datas);
            MyAdapter adapter = new MyAdapter(this, datas, false);
            final LinearLayoutManager layoutManager = new LinearLayoutManager(this);
            layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
            recyclerView.setLayoutManager(layoutManager);

        //        recyclerView.removeItemDecoration(new GroupHeaderItemDecoration(this)
//                .setTags(tags)
//                .setGroupHeaderHeight(30)
//                .setGroupHeaderLeftPadding(20));

            recyclerView.addItemDecoration(new GroupHeaderItemDecoration(this)
                    .setTags(tags)
                    .setGroupHeaderHeight(30)
                    .setGroupHeaderLeftPadding(20)
            );
            recyclerView.addItemDecoration(new DivideItemDecoration().setTags(tags));
            recyclerView.setAdapter(adapter);
`

**Comment by Likeyong** [comment]
> 我大致是这样写的,但是不行,应该怎么改呢?
> ` SortHelper sortHelper = new SortHelper() {
> @override
> public String sortField(ItemData data) {
> return data.getTitle();
> }
> };
> 
> ```
>     //todo: 注意手机号或姓名为null的情况
>         sortHelper.sortByLetter(datas);
>         final List<String> tags = sortHelper.getTags(datas);
>         MyAdapter adapter = new MyAdapter(this, datas, false);
>         final LinearLayoutManager layoutManager = new LinearLayoutManager(this);
>         layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
>         recyclerView.setLayoutManager(layoutManager);
> 
>     //        recyclerView.removeItemDecoration(new GroupHeaderItemDecoration(this)
> ```
> 
> // .setTags(tags)
> // .setGroupHeaderHeight(30)
> // .setGroupHeaderLeftPadding(20));
> 
> ```
>         recyclerView.addItemDecoration(new GroupHeaderItemDecoration(this)
>                 .setTags(tags)
>                 .setGroupHeaderHeight(30)
>                 .setGroupHeaderLeftPadding(20)
>         );
>         recyclerView.addItemDecoration(new DivideItemDecoration().setTags(tags));
>         recyclerView.setAdapter(adapter);
> ```
> 
> `
把你移除分割线代码
 //        recyclerView.removeItemDecoration(new GroupHeaderItemDecoration(this)
换成
for (int i = 0 ; i <listView.getItemDecorationCount() ; i++){
				listView.removeItemDecorationAt(i);
			}

因为你removeItemDecoration 传递的是你new出来的分割线,所以并没有移除你之前添加的分割线

**Comment by roybill** [comment]
不行呢,我现在手动加了一个手机号码,但是不输入姓名,也就是姓名为空,直接运行会空指针,提示  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference,控制台指向这一行代码: sortHelper.sortByLetter(datas);
代码我按你那样说改成这样:
`      SortHelper<ItemData> sortHelper = new SortHelper<ItemData>() {
            @Override
            public String sortField(ItemData data) {
                return data.getTitle();
            }
        };

        //todo: 注意手机号或姓名为null的情况
        sortHelper.sortByLetter(datas);
        final List<String> tags = sortHelper.getTags(datas);
        MyAdapter adapter = new MyAdapter(this, datas, false);
        final LinearLayoutManager layoutManager = new LinearLayoutManager(this);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(layoutManager);

        for (int i = 0; i < recyclerView.getItemDecorationCount(); i++) {
            recyclerView.removeItemDecorationAt(i);
        }
        recyclerView.addItemDecoration(new GroupHeaderItemDecoration(this)
                .setTags(tags)
                .setGroupHeaderHeight(30)
                .setGroupHeaderLeftPadding(20)
        );
        recyclerView.addItemDecoration(new DivideItemDecoration().setTags(tags));
        recyclerView.setAdapter(adapter);`

**Comment by roybill** [comment]
我试了一下,姓名不为空,手机号码为空的时候正常,但是姓名为空,手机号码不为空的时候就提示这里空指针了sortHelper.sortByLetter(datas);  你可以试着创建一个联系人,姓名不输入,只输手机号,然后保存,再打开自己创建的demo就报错了

**Comment by Likeyong** [comment]
> 不行呢,我现在手动加了一个手机号码,但是不输入姓名,也就是姓名为空,直接运行会空指针,提示 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference,控制台指向这一行代码: sortHelper.sortByLetter(datas);
> 代码我按你那样说改成这样:
> ` SortHelper sortHelper = new SortHelper() {
> @override
> public String sortField(ItemData data) {
> return data.getTitle();
> }
> };
> 
> ```
>     //todo: 注意手机号或姓名为null的情况
>     sortHelper.sortByLetter(datas);
>     final List<String> tags = sortHelper.getTags(datas);
>     MyAdapter adapter = new MyAdapter(this, datas, false);
>     final LinearLayoutManager layoutManager = new LinearLayoutManager(this);
>     layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
>     recyclerView.setLayoutManager(layoutManager);
> 
>     for (int i = 0; i < recyclerView.getItemDecorationCount(); i++) {
>         recyclerView.removeItemDecorationAt(i);
>     }
>     recyclerView.addItemDecoration(new GroupHeaderItemDecoration(this)
>             .setTags(tags)
>             .setGroupHeaderHeight(30)
>             .setGroupHeaderLeftPadding(20)
>     );
>     recyclerView.addItemDecoration(new DivideItemDecoration().setTags(tags));
>     recyclerView.setAdapter(adapter);`
> ```

你现在是根据名字排序的把,你把名字设置为空,在获取名字的首字母的时候肯定会为空

**Comment by roybill** [comment]
@Likeyong   是的,那如果有些用户手机就是存了一个空的姓名,这样该怎么解决呢?我试了空判断也不好加

**Comment by Likeyong** [comment]
> @Likeyong 是的,那如果有些用户手机就是存了一个空的姓名,这样该怎么解决呢?我试了空判断也不好加

我不记得这个框架有没有对这个进行处理.但是你可以在设置数据给adapter之前把所有名字为空的名字,设置成"#"这样的或者直接过滤掉名字为空的数据

**Comment by roybill** [comment]
这样应该可以了,姓名为空的话就不加到通讯录
`  ArrayList<HashMap<String, String>> hashMaps = readContact();
        for (int i = 0; i < hashMaps.size(); i++) {
            String name = hashMaps.get(i).get("name");
            if(name!=null){
                //            String number = hashMaps.get(i).get("phone").replace(" ", "").replace("-","");
                String number = hashMaps.get(i).get("phone");   //todo: 1.动态权限问题, 2.注意手机号码之间有- 和空格问题  (可以在获取到号码后再进行替换)

//            ContactsBean contactsBean = mDatas.get(i);
                ItemData contactsBean = new ItemData(name, number);
//            contactsBean.setName(name);
//            contactsBean.setNumber(number);
//            contactsBean.setTitle(name);
                datas.add(contactsBean);
            }`
