### ISSUE TITLE
SideBar 每个字母间的间距能否暴露出一个属性给开发者

### ISSUE THREAD

**Issue by Likeyong** [Othershe/GroupIndexLib#4]
![screenshot_2018-05-24-19-18-40-395_com nj wellsig](https://user-images.githubusercontent.com/26381714/40482462-7c475340-5f87-11e8-88e9-91551c65a74b.png)
这里sidebar 字母挤在一起， 但是有的时候是均匀分散的，看了一下代码，是通过drawText 实现的，想能不能在drawText 加上间距 。

**Comment by Likeyong** [comment]
其次还遇到一个问题，就是 sidebar 索引更新不及时，必须触摸sidebar 之后，字母索引才会改变

**Comment by shehuan** [comment]
1、xml中`SideBar`的`android:layout_height="wrap_content"`时会进行默认的测量，所以字母会有挤在一起的感觉，这种情况加间距也简单
2、不触摸，没有事件，怎么改变？还是我理解错了？

**Comment by Likeyong** [comment]
就是通过settag   设置新的tag  心目的索引总是没变，必须触摸之后才会显示新的tag，我通过postInvalidate，每次设置后新tag就会重新绘制。

我看了代码确实是只要是wrapcontent  ，就会重新计算高度。但是有时候我给sidebar 设置了固定的高度，字母还是被挤在一起
