### ISSUE TITLE
关于sidebar 触摸转跳逻辑是不是存在一点问题

### ISSUE THREAD

**Issue by Likeyong** [Othershe/GroupIndexLib#5]
` if (onSideBarTouchListener != null) {
                        for (int i = 0; i < tags.size(); i++) {
                            if (indexArray[pos].equals(tags.get(i))) {
                                onSideBarTouchListener.onTouch(indexArray[pos], i);
                                break;
                            }
                            if (i == tags.size() - 1) {
                                onSideBarTouchListener.onTouch(indexArray[pos], -1);
                            }
                        }
                    }`

这里判断  触摸回调里面 position值的时候   传入的 i  是当前触摸字母在 tag中的位置。那么这个i的取值只可能小于tag.size（）；  但是我们的数据list  的大小事很有可能大于tag.size();就会出现转跳位置错误的情况。因为传入的i，的值取值范围是【-1，tag.size】.  我也确实碰到了这个问题。

下面是我的解决方案：
` sideBar.setOnSideBarTouchListener(newTag, new OnSideBarTouchListener() {
            @Override
            public void onTouch(String s, int i) {
                LinearLayoutManager layoutManager = (LinearLayoutManager) recyclerView.getLayoutManager();
                int position = 0 ; ;
                for (int index = 0; index < companyMemberList.size(); index++) {
                    BaseItem item = companyMemberList.get(index);
                    if (s.equals(item.getTag())) {
                        position = companyMemberList.indexOf(item);
                        break;
                    }
                }
                layoutManager.scrollToPositionWithOffset(position, 0);
            }`

希望能得到答复谢谢

**Comment by shehuan** [comment]
1、按照目前的实现`tags`的数量和`数据list`的数量相同，具体见`SortHelper.getTags()`；由于`tags`里会有重复的`tag`，这个可以优化的！
2、`i==-1`是没找到的情况，需要在`onTouch()`里特殊处理，`i==tag.size`不可能成立吧

**Comment by Likeyong** [comment]
tag确实是会重复，我用set处理了重复的tag，这样就导致了tag的数目与list不同的情况。sidebar  提供了手动设置tag，不知这和情况是否也会导致tag与list不同

**Comment by SheHuan** [comment]
处理重复tag不要用set，要不然就对应不上tag第一次出现的位置了，可以考虑使用map保存tag和首次出现的位置 shehuan.dev 邮箱：shehuan.dev@gmail.com 签名由 网易邮箱大师 定制 在2018年07月26日 19:21，Likeyong 写道： tag确实是会重复，我用set处理了重复的tag，这样就导致了tag的数目与list不同的情况。sidebar 提供了手动设置tag，不知这和情况是否也会导致tag与list不同 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by shehuan** [comment]
处理重复tag不要用set，要不然就对应不上tag第一次出现的位置了，可以考虑使用map保存tag和首次出现的位置

**Comment by Likeyong** [comment]
好的，谢谢
